---
- name: Check disk usage
  hosts: all
  gather_facts: no

  tasks:
    - name: Run df -h
      command: df -h /
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "{{ inventory_hostname }} -> {{ disk_usage.stdout_lines }}"
