---
- name: Fix apt and install nginx
  hosts: all
  become: yes

  tasks:
    - name: Clean apt cache
      command: apt-get clean

    - name: Update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Fix broken packages
      command: apt-get install -f -y

    - name: Install nginx
      apt:
        name: nginx
        state: present
