---
- name: Update and upgrade Ubuntu nodes
  hosts: all
  become: yes
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Run apt upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
